### ISSUE TITLE
GitHub Like Emoji

### ISSUE THREAD

**Issue by EmpireWorld** [iBicha/EmojiTexture#6]
Using GitHub like emoji codes for instantiating EmojiTexture class, for example instead of doing:

```csharp
material.mainTexture = new EmojiTexture("❤");
```

We can do this:

```csharp
material.mainTexture = new EmojiTexture(":heart:");
```

Thanks.

**Comment by iBicha** [comment]
Hi @EmpireWorld 
Thank you for the suggestion! Markdown emojis are probably useful, could be a simple helper class that maps `:heart:` to `❤`. Currently working on TextMesh Pro support, and this will be planned right after.

**Comment by iBicha** [comment]
I might end up using the github emoji API as a map.
https://api.github.com/emojis
The file names indicate the unicode value.
Could also work as a fallback on other platforms

**Comment by iBicha** [comment]
Update on this: This is a WIP, kinda working, but I'm making some changes and that's including:

- Mapping emoji names to unicode
- Support for other platforms: download images when they are not natively supported (e.g. the editor)
- Have an callback event for when the emoji image is downloaded (or if it fails, if no internet etc)

**Comment by iBicha** [comment]
Fixed by last commit.
